name: Test push
on: [push]
jobs:
  This-Is-First-job:
    runs-on: ubuntu-latest
    steps:
        - name: Show creds
          run: echo "${{ secrets.IP }} ${{ secrets.USERNAME}} ${{secrets.PRIVATE_KEY}} . Today is $DAY_OF_WEEK!"
        - name: Deploy to Staging server
          uses: appleboy/ssh-action@master
          with: 
            host: ${{ secrets.IP }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            password: ""
            script: whoami
    
