name: Test push
on: [push]
jobs:
  This-Is-First-job:
    runs-on: ubuntu-latest
    steps:
        - name: Show creds
          run: echo "${{ secrets.IP }} ${{ secrets.USERNAME}} ${{secrets.PRIVATE_KEY}} . Today is $DAY_OF_WEEK!"
        - name: Deploy to Staging server
          uses: appleboy/ssh-action@master
          with: 
            host: ${{ secrets.IP }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            password: ""
            script: |
              sudo su
              cd /srv/poker_playhouse
              git pull origin master
              cd client/
              sudo yarn
              sudo yarn build
              cd ..
              pm2 stop pokerhouse
              pm2 start pokerhouse
            
    
