name: Test push
on: [push]
jobs:
  This-Is-First-job:
    runs-on: ubuntu-latest
    steps:
        - name: Deploy to Staging server
          uses: appleboy/ssh-action@master
          with: 
            host: ${{ secrets.IP }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.PRIVATE_KEY }}
            script: whoami
    
