name: Test push
on: [push]
jobs:
  This-Is-First-job:
    runs-on: ubuntu-latest
    steps:
        - name: Show creds
          run: echo "${{ secrets.TEST_SECRET_REPOSITORY.IP }} ${{ secrets }}. Today is $DAY_OF_WEEK!"
        - name: Deploy to Staging server
          uses: appleboy/ssh-action@master
          with: 
            host: ${{ secrets.TEST_SECRET_REPOSITORY.IP }}
            username: ${{ secrets.TEST_SECRET_REPOSITORY.USER }}
            key: ${{ secrets.TEST_SECRET_REPOSITORY.PRIVATE_KEY }}
            script: whoami
    
